name: npl-2024a
channels:
  - conda-forge
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accessible-pygments=0.0.4
  - affine=2.4.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - alabaster=0.7.16
  - alsa-lib=1.2.10
  - annotated-types=0.6.0
  - ansiwrap=0.8.4
  - antimeridian=0.3.5
  - antlr-python-runtime=4.11.1
  - anyio=4.2.0
  - aom=3.7.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arm_pyart=1.17.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - astroid=3.0.2
  - astropy=6.0.0
  - astropy-iers-data=0.2024.1.8.0.30.55
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.5
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.5
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.35
  - aws-c-mqtt=0.9.8
  - aws-c-s3=0.3.22
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.4
  - aws-sdk-cpp=1.11.182
  - babel=2.14.0
  - beautifulsoup4=4.12.2
  - black=23.12.1
  - bleach=6.1.0
  - blosc=1.21.5
  - bokeh=3.3.3
  - boto3=1.34.18
  - botocore=1.34.18
  - bottleneck=1.3.7
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.25.0
  - c-blosc2=2.12.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cartopy=0.22.0
  - cdsapi=0.6.1
  - celluloid=0.2.0
  - certifi=2024.2.2
  - cf-units=3.2.0
  - cf_xarray=0.8.7
  - cffi=1.16.0
  - cfgrib=0.9.10.4
  - cfitsio=4.3.0
  - cftime=1.6.3
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - cmaps=2.0.1
  - cmcrameri=1.8
  - cmocean=3.0.3
  - cmweather=0.3.2
  - colorama=0.4.6
  - colorcet=3.0.1
  - colorspacious=1.1.2
  - comm=0.2.1
  - contextily=1.5.0
  - contourpy=1.2.0
  - cryptography=41.0.7
  - curl=8.4.0
  - cycler=0.12.1
  - cython=3.0.7
  - cytoolz=0.12.2
  - dask=2024.1.0
  - dask-core=2024.1.0
  - dask-jobqueue=0.8.2
  - dask-labextension=7.0.0
  - dask-mpi=2022.4.0
  - dataclasses=0.8
  - datashader=0.16.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - descartes=1.1.0
  - dill=0.3.7
  - distributed=2024.1.0
  - docopt=0.6.2
  - docrep=0.3.2
  - docutils=0.17.1
  - eccodes=2.32.1
  - entrypoints=0.4
  - eofs=1.4.1
  - esmf=8.4.2
  - esmpy=8.4.2
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fasteners=0.17.3
  - fastprogress=1.0.3
  - ffmpeg=6.1.0
  - findlibs=0.0.5
  - fiona=1.9.5
  - flox=0.8.7
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.2
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - future=0.18.3
  - gdal=3.7.2
  - gdk-pixbuf=2.42.10
  - geocat-comp=2023.12.0
  - geocat-viz=2023.03.0
  - geographiclib=1.52
  - geopandas-base=0.14.2
  - geopy=2.4.1
  - geos=3.12.0
  - geotiff=1.7.1
  - geoviews=1.11.0
  - geoviews-core=1.11.0
  - gettext=0.21.1
  - gflags=2.2.2
  - ghp-import=2.1.0
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - globus-cli=3.23.0
  - globus-sdk=3.34.0
  - glog=0.6.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - graphviz=9.0.0
  - greenlet=3.0.3
  - gsl=2.7
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - gsw=3.6.17
  - gtk2=2.24.33
  - gts=0.7.6
  - h5netcdf=1.3.0
  - h5py=3.10.0
  - harfbuzz=8.3.0
  - hdf4=4.2.15
  - hdf5=1.14.2
  - hdfeos2=2.20
  - hdfeos5=5.1.16
  - holoviews=1.18.1
  - hvplot=0.9.1
  - icu=73.2
  - idna=3.6
  - imagecodecs=2023.9.18
  - imageio=2.33.1
  - imagesize=1.4.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intake=0.7.0
  - intake-esm=2023.11.10
  - intake-xarray=0.7.0
  - ipykernel=6.28.0
  - ipympl=0.9.3
  - ipython=8.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - iris=3.7.0
  - isoduration=20.11.0
  - isort=5.13.2
  - jasper=4.0.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - json-c=0.17
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter-book=0.15.1
  - jupyter-cache=0.6.1
  - jupyter-lsp=2.2.1
  - jupyter-server-proxy=4.1.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.4
  - jupyter_server_terminals=0.5.1
  - jupyterlab=4.0.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - jxrlib=1.1
  - kealib=1.5.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lat_lon_parser=1.3.0
  - latexcodec=2.0.1
  - lazy_loader=0.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - ldcpy=0.17
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=13.0.0
  - libass=0.17.1
  - libavif16=1.0.3
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.19
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgd=2.3.3
  - libgdal=3.7.2
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.58.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopencv=4.8.1
  - libopenvino=2023.1.0
  - libopenvino-auto-batch-plugin=2023.1.0
  - libopenvino-auto-plugin=2023.1.0
  - libopenvino-hetero-plugin=2023.1.0
  - libopenvino-intel-cpu-plugin=2023.1.0
  - libopenvino-intel-gpu-plugin=2023.1.0
  - libopenvino-ir-frontend=2023.1.0
  - libopenvino-onnx-frontend=2023.1.0
  - libopenvino-paddle-frontend=2023.1.0
  - libopenvino-pytorch-frontend=2023.1.0
  - libopenvino-tensorflow-frontend=2023.1.0
  - libopenvino-tensorflow-lite-frontend=2023.1.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.5
  - libprotobuf=4.24.3
  - libre2-11=2023.06.02
  - librsvg=2.56.3
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libudunits2=2.2.28
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.20.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.12.4
  - libzip=1.10.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.2
  - llvmlite=0.41.1
  - locket=1.0.0
  - looseversion=1.3.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.5.2
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.2
  - mercantile=1.2.1
  - metpy=1.6.1
  - minizip=4.0.3
  - mistune=3.0.2
  - mpg123=1.32.4
  - mpi=1.0
  - mpi4py=3.1.5
  - mpich=4.1.2
  - msgpack-python=1.0.7
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - munch=4.0.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - myst-nb=0.17.2
  - myst-parser=0.18.1
  - nbclient=0.7.4
  - nbconvert-core=7.14.1
  - nbformat=5.9.2
  - nc-time-axis=1.4.1
  - ncar-jobqueue=2021.4.14
  - ncl=6.6.2
  - nco=5.1.9
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - netcdf-fortran=4.6.1
  - netcdf4=1.6.5
  - nettle=3.9.1
  - networkx=3.2.1
  - nomkl=1.0
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.96
  - numba=0.58.1
  - numcodecs=0.12.1
  - numexpr=2.8.8
  - numpy=1.26.3
  - numpy_groupies=0.10.2
  - ocgis=2.1.1
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - open-radar-data=0.0.7
  - opencv=4.8.1
  - openh264=2.4.0
  - openjpeg=2.5.0
  - openssl=3.3.0
  - orc=1.9.0
  - overrides=7.4.0
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - panel=1.3.6
  - pango=1.50.14
  - papermill=2.4.0
  - param=2.0.1
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pint=0.23
  - pip=23.3.2
  - pixman=0.43.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - ply=3.11
  - pooch=1.8.0
  - pop-tools=2023.6.0
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=15.5
  - proj=9.3.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - properscoring=0.1
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-opencv=4.8.1
  - pyarrow=13.0.0
  - pyarrow-hotfix=0.6
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pycparser=2.21
  - pyct=0.5.0
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pydap=3.4.0
  - pydata-sphinx-theme=0.15.1
  - pyerfa=2.0.1.1
  - pygments=2.17.2
  - pygraphviz=1.11
  - pygrib=2.1.4
  - pyhdf=0.11.3
  - pyjwt=2.8.0
  - pylint=3.0.3
  - pynco=1.1.0
  - pyngl=1.6.1
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-eccodes=1.6.1
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python-wget=3.2
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyviz_comms=3.0.0
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - rasterio=1.3.9
  - rav1e=0.6.6
  - rdma-core=49.0
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.32.1
  - requests=2.31.0
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.16.2
  - rtree=1.1.0
  - s2n=1.3.56
  - s3fs=0.4.2
  - s3transfer=0.10.0
  - scikit-image=0.22.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.1
  - seaborn-base=0.13.1
  - seawater=3.3.4
  - send2trash=1.8.2
  - setuptools=69.0.3
  - setuptools-scm=8.0.4
  - setuptools_scm=8.0.4
  - shapely=2.0.2
  - simpervisor=1.0.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparse=0.15.1
  - spatialpandas=0.4.10
  - sphinx=5.0.2
  - sphinx-book-theme=1.0.1
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.3.0
  - sphinx-external-toc=0.3.1
  - sphinx-jupyterbook-latex=0.5.2
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.2.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-bibtex=2.5.0
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.25
  - sqlite=3.44.2
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - svt-av1=1.7.0
  - tabulate=0.9.0
  - tbb=2021.11.0
  - tblib=3.0.0
  - tempest-remap=2.2.0
  - tenacity=8.2.3
  - terminado=0.18.0
  - textwrap3=0.9.2
  - threadpoolctl=3.2.0
  - tifffile=2023.12.9
  - tiledb=2.16.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - tobac=1.5.2
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.3
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - trackpy=0.6.1
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzcode=2023d
  - tzdata=2023d
  - uc-micro-py=1.0.2
  - ucx=1.15.0
  - udunits2=2.2.28
  - uri-template=1.3.0
  - uriparser=0.9.7
  - urllib3=1.26.18
  - uxarray=2024.04.0
  - versioneer=0.29
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - webob=1.8.7
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - wrapt=1.16.0
  - wrf-python=1.3.4.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2023.12.0
  - xarray-datatree=0.0.13
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xesmf=0.8.2
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xinvert=0.1.3
  - xkeyboard-config=2.40
  - xmltodict=0.13.0
  - xorg-fixesproto=5.0
  - xorg-imake=1.0.7
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxaw=1.0.14
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxmu=1.1.3
  - xorg-libxpm=3.5.17
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-makedepend=1.0.8
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xradar=0.4.2
  - xrft=1.0.1
  - xskillscore=0.0.24
  - xxhash=0.8.2
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zarr=2.16.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
prefix: /glade/u/apps/opt/conda/envs/npl-2024a
