name: Update CESM run matrix

on:
  push:
    paths:
      - "atm_in_files/**"
      - "scripts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Generate matrix
        run: python scripts/generate_exp_matrix.py

      - name: Commit updated matrix
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/run_matrix.json
          git commit -m "Update CESM run matrix" || echo "No changes"
          git push